profile: 
  author: 
  avatar: https://cdn.patrickwu.space/base/me.jpg
  description: Patrick Wu

favicon: https://cdn.patrickwu.space/base/icon.png

footer:
  author: Patrick WU Jinming
  since: 2008