name: CD
on: [push]
jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Generate
        run: |
          ./node_modules/bin/hexo clean
          ./node_modules/bin/hexo generate
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GIT_DEPLOY_KEY }}
        run: |
          git config --global user.email "me@patrickwu.space"
          git config --global user.name "Jinming Wu, Patrick"
          git clone --depth 1 https://patrick330602:$GH_TOKEN@github.com/patrick330602/patrick330602.github.io.git website
          cp -rf ./public/* ./website/
          git --git-dir=./website/.git --work-tree=./website add -A
          git --git-dir=./website/.git --work-tree=./website commit -m "blog update at $(date)"
          git --git-dir=./website/.git --work-tree=./website push