name: CD
on: [push]
jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Pre-configuration
        run: |
          yarn
          yarn global add hexo-cli
      - name: Generate
        run: |
          hexo clean
          hexo generate
          cp .htaccess ./public
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "public/*,public/.*"
          target: "/var/www/posts/"
          overwrite: true
          strip_components: 1